
CREATE DATABASE PROGRAMACION_PHP;
USE PROGRAMACION_PHP;

CREATE TABLE EVIDENCIA(
	ID_EVIDENCIA BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NULL,
    DESCRIPCIÓN VARCHAR(500) NULL,
    TIPO VARCHAR(50) NULL,
    FECHA_CREACION_EVIDENCIA DATETIME NULL,
    FECHA_REGISTRO_EVIDENCIA DATETIME NULL,
    AUTORES VARCHAR(50) NULL,
    OBSERVACION VARCHAR(500) NULL,
	PARALELO VARCHAR(20) NULL,
    MERIDIANO VARCHAR(20) NULL,
    ESTADO VARCHAR(30) NULL
);

CREATE TABLE EVIDENCIA_DETALLE(
	ID_EVIDENCIA_DETALLE BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20),
    USUARIO_MODIFICACION VARCHAR(20) NOT NULL,
    FECHA_MODIFICACION DATETIME NOT NULL, 
    ESTADO_ANTERIOR VARCHAR(30) NULL,
    ESTADO_ACTUAL VARCHAR(30) NULL
);

ALTER TABLE EVIDENCIA_DETALLE ADD CONSTRAINT FK_EVIDENCIA_DETALLE_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;