drop DATABASE if exists SISEVID;
CREATE DATABASE SISEVID;
USE SISEVID;

--  creacion de las tablas   ------------------------------------------------------------------------------------------

CREATE TABLE lugar_geografico(
	ID_lugar_geografico BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
    PARALELO VARCHAR(20) NULL,
    MERIDIANO VARCHAR(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE EVIDENCIA(
	ID_EVIDENCIA BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NULL,
    DESCRIPCIÓN VARCHAR(500) NULL,
    TIPO VARCHAR(50) NULL,
    TIPO_ARCHIVO VARCHAR(50) NULL,
    FECHA_CREACION_EVIDENCIA DATE NULL,
    FECHA_REGISTRO_EVIDENCIA DATE NULL,
    AUTORES VARCHAR(50) NULL,
    OBSERVACION VARCHAR(500) NULL,
	ID_lugar_geografico BIGINT(20) NULL,
    ESTADO VARCHAR(30) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
);
ALTER TABLE EVIDENCIA ADD CONSTRAINT FK_EVIDENCIA_FK1 FOREIGN KEY (ID_lugar_geografico)
      REFERENCES lugar_geografico (ID_lugar_geografico) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE EVIDENCIA_DETALLE(
	ID_EVIDENCIA_DETALLE BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20) NOT NULL,
    USUARIO_MODIFICACION VARCHAR(20) NOT NULL,
    FECHA_MODIFICACION DATETIME NOT NULL, 
    ESTADO_ANTERIOR VARCHAR(30) NULL,
    ESTADO_ACTUAL VARCHAR(30) NULL
);
ALTER TABLE EVIDENCIA_DETALLE ADD CONSTRAINT FK_EVIDENCIA_DETALLE_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;
 
 
CREATE TABLE TITULO(
	ID_TITULO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,  
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE CAPITULO (
	ID_CAPITULO  BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_TITULO BIGINT(20) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
);
ALTER TABLE CAPITULO ADD CONSTRAINT FK_CAPITULO_FK1 FOREIGN KEY (ID_TITULO)
      REFERENCES TITULO (ID_TITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

 CREATE TABLE CONDICION(
	ID_CONDICION BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_CAPITULO BIGINT(20) NOT NULL,  
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE CONDICION ADD CONSTRAINT FK_CONDICION_FK1 FOREIGN KEY (ID_CAPITULO)
      REFERENCES CAPITULO (ID_CAPITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;


CREATE TABLE SECCION(
	ID_SECCION BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_CAPITULO BIGINT(20) NOT NULL,  
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE SECCION ADD CONSTRAINT FK_SECCION_FK1 FOREIGN KEY (ID_CAPITULO)
      REFERENCES CAPITULO (ID_CAPITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE ARTICULO(
	ID_ARTICULO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_SECCION BIGINT(20) NOT NULL,   
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
);
ALTER TABLE ARTICULO ADD CONSTRAINT FK_ARTICULO_FK1 FOREIGN KEY (ID_SECCION)
      REFERENCES SECCION (ID_SECCION) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE LITERAL(
	ID_LITERAL BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_ARTICULO BIGINT(20) NULL,
	CODIGO VARCHAR(3) NOT NULL,    
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE LITERAL ADD CONSTRAINT FK_LITERAL_FK1 FOREIGN KEY (ID_ARTICULO)
      REFERENCES ARTICULO (ID_ARTICULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE PARAGRAFO(
	ID_PARAGRAFO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_CAPITULO BIGINT(20) NULL,
	CODIGO VARCHAR(3) NOT NULL,    
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE PARAGRAFO ADD CONSTRAINT FK_PARAGRAFO_FK1 FOREIGN KEY (ID_CAPITULO)
      REFERENCES cAPITULO (ID_CAPITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE NUMERAL(
	ID_NUMERAL BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_LITERAL BIGINT(20) NULL,
	CODIGO VARCHAR(3) NOT NULL,    
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE NUMERAL ADD CONSTRAINT FK_NUMERAL_FK1 FOREIGN KEY (ID_LITERAL)
      REFERENCES LITERAL (ID_LITERAL) ON DELETE RESTRICT ON UPDATE RESTRICT;

--  relaciones muchos a muchos     ------------------------------------------------------------------------------------------

CREATE TABLE evidencia_articulo(
	ID_evidencia_articulo BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_evidencia BIGINT(20) NULL,
    ID_articulo BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE evidencia_articulo ADD CONSTRAINT FK_evidencia_articulo_FK1 FOREIGN KEY (ID_evidencia)
      REFERENCES evidencia (ID_evidencia) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE evidencia_articulo ADD CONSTRAINT FK_evidencia_articulo_FK2 FOREIGN KEY (ID_articulo)
      REFERENCES articulo (ID_articulo) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
CREATE TABLE evidencia_literal(
	ID_evidencia_literal BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_evidencia BIGINT(20) NULL,
    ID_literal BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE evidencia_literal ADD CONSTRAINT FK_evidencia_literal_FK1 FOREIGN KEY (ID_evidencia)
      REFERENCES evidencia (ID_evidencia) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE evidencia_literal ADD CONSTRAINT FK_evidencia_literal_FK2 FOREIGN KEY (ID_literal)
      REFERENCES literal (ID_literal) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
CREATE TABLE evidencia_numeral(
	ID_evidencia_numeral BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_evidencia BIGINT(20) NULL,
    ID_numeral BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE evidencia_numeral ADD CONSTRAINT FK_evidencia_numeral_FK1 FOREIGN KEY (ID_evidencia)
      REFERENCES evidencia (ID_evidencia) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE evidencia_numeral ADD CONSTRAINT FK_evidencia_numeral_FK2 FOREIGN KEY (ID_numeral)
      REFERENCES numeral (ID_numeral) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
CREATE TABLE evidencia_paragrafo(
	ID_evidencia_paragrafo BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_evidencia BIGINT(20) NULL,
    ID_paragrafo BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE evidencia_paragrafo ADD CONSTRAINT FK_evidencia_paragrafo_FK1 FOREIGN KEY (ID_evidencia)
      REFERENCES evidencia (ID_evidencia) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE evidencia_paragrafo ADD CONSTRAINT FK_evidencia_paragrafo_FK2 FOREIGN KEY (ID_paragrafo)
      REFERENCES paragrafo (ID_paragrafo) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
--     usuarios -----------------------------------

CREATE TABLE usuario_info_contacto(
	ID_usuario_info_contacto BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    tipo_documento VARCHAR(100) NOT NULL,
    numero_documento VARCHAR(100) NOT NULL,
    nombres VARCHAR(100) NOT NULL,    
	apellidos VARCHAR(100) NOT NULL,
    numero_contacto VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE usuario_roles(
	ID_usuario_roles BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE usuario(
	ID_usuario BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_usuario_info_contacto BIGINT(20) not NULL,
    ID_usuario_roles BIGINT(20) not NULL,
    usuario VARCHAR(10) NOT NULL,    
	contraseña VARCHAR(10) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE usuario ADD CONSTRAINT FK_usuario_FK1 FOREIGN KEY (ID_usuario_info_contacto)
      REFERENCES usuario_info_contacto (ID_usuario_info_contacto) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE usuario ADD CONSTRAINT FK_usuario_FK2 FOREIGN KEY (ID_usuario_roles)
      REFERENCES usuario_roles (ID_usuario_roles) ON DELETE RESTRICT ON UPDATE RESTRICT;

